### PR TITLE
Splunk 7.0.0

### PR DESCRIPTION
**Pull request by outcoldman**

### CODE REVIEW

**Review by halr9000 — APPROVED** [review]
LGTM

**Comment by outcoldman** [comment]
@halr9000 btw, seems like somebody will need to build it and push it on hub.docker.com

**Comment by outcoldman** [comment]
pinged @michaelwilde and it is done! thank you guys!

**Comment by halr9000** [comment]
No, thank you, Den! Glad to see you pop up!
________________________________

**Pull request merged**
