### PR TITLE
Splunk 7.0.2

### PR DESCRIPTION
**Pull request by outcoldman**
Time to upgrade to 7.0.2

Basically did

```
s/7.0.1/7.0.2/g
```

And updated Dockerfile to use 7.0.2 instead

cc @mchene @michaelwilde @halr9000

### CODE REVIEW

**Comment by halr9000** [comment]
thx @outcoldman !

**Comment by outcoldman** [comment]
Please don't forget to deploy it! https://hub.docker.com/r/splunk/splunk/tags/

**Comment by michaelwilde** [comment]
I'll do it now.

**Comment by michaelwilde** [comment]
@outcoldman forwarder and indexer 7.0.2 are published to hub and registry as latest and 7.0.2

**Pull request merged**
