### PR TITLE
Splunk 7.1.0

### PR DESCRIPTION
**Pull request by outcoldman**
Bump to 7.1.0
cc @mchene @halr9000 @michaelwilde

### CODE REVIEW

**Comment by outcoldman** [comment]
This will make life harder

```
Password must contain at least:
   * 8 total printable ASCII character(s).

This appears to be your first time running this version of Splunk.

An Admin password must be set before installation proceeds.
tcgetattr: Inappropriate ioctl for device
WARNING: error changing terminal modes - password will echo!
Please enter a new password:
```

You need to run it now with `-it` for the first time to set the password

```
docker run --rm --publish 8000 --env SPLUNK_START_ARGS="--accept-license" -it splunk:7.1.0

This appears to be your first time running this version of Splunk.

An Admin password must be set before installation proceeds.
Password must contain at least:
   * 8 total printable ASCII character(s).
Please enter a new password:
Please confirm new password:

...
```

**Comment by michaelwilde** [comment]
Made a 7.1.0 branch... we can merge this in with master whenever someone thinks it should be tagged "latest"

**Comment by halr9000** [comment]
Let's create an issue to track what to do about 7.1. I'm communicating with some folks internally as well.

**Comment by darksheer** [comment]
Any updates on the 7.1 release?

**Pull request merged**
