### PR TITLE
updated for Splunk v6.5.2 build 67571ef4b87d

### PR DESCRIPTION
**Pull request by michaelwilde**
Made the build and version changes for 6.5.2 so we can have an updated image on docker hub

### CODE REVIEW

**Review by halr9000 — COMMENTED** [review]
LGTM.  Did you test the monitor tag app? I will do so shortly.

**Comment by michaelwilde** [comment]
It's in a different repo, I haven't modified that one yet… I'll probably do that today or you can

-michael

Michael Wilde
Chief of Black Ops and White Lies
Office of Field Technology, Splunk
thewilde@splunk.com<mailto:thewilde@splunk.com>
(512) 524-9742

http://www.splunk.com

splunk> docker, bro.




On Fri, Jan 27, 2017 at 8:44 AM -0600, "Hal Rottenberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


@halr9000 commented on this pull request.

LGTM. Did you test the monitor tag app? I will do so shortly.

**Comment by halr9000** [comment]
Duh. On it. This PR passes my smoke test, now using it to build images in https://github.com/splunk/docker-itmonitoring

**Comment by mchene** [comment]
Reviewed by Den Gladkikh, Scott Centoni, and myself.

**Pull request merged**
