### PR TITLE
Version 6.5.1

### PR DESCRIPTION
**Pull request by btorresgil**
Adds support for Splunk version 6.5.1

### CODE REVIEW

**Comment by JewelPengin** [comment]
👍

**Comment by halr9000** [comment]
LGTM, but haven't run any tests.

**Comment by halr9000** [comment]
FTR, I'm told that we are holding on merging this PR while Splunk iterates on automating the steps on our side. Sorry for the apparent lack of activity @JewelPengin & @btorresgil . I hope to see this in place very soon. Will see if the PM can share anything more firm, ok?

**Comment by halr9000** [comment]
@mchene can you add anything at this time? I had another customer ask for status, so it seems best to put it here.

**Comment by btorresgil** [comment]
@halr9000 @mchene Looks like this problem is getting away from you.  No updates to Splunk docker image, but people keep submitting pull requests for updates that are not getting merged.  Any updates on when the Splunk release process will include automatic updates to the docker image too?

Other pull requests like this one:
#38 Upgrade to Splunk 6.5.3 Release
#41 updated forwarder and enterprise for 6.5.3
#42 Upgrade to 6.6.0

**Comment by halr9000** [comment]
@btorresgil hear you loud and clear, am trying to get an update.

**Comment by halr9000** [comment]
No longer needed

**Pull request closed without merging**
